const data = [
  {
    name: 'Landing Page',
    ideas: [
      { title: 'Product launch page', prompt: 'Build a product launch landing page for our new AI writing assistant called "QuillSpark." Purpose: announce the launch, highlight key benefits, and drive early-access signups. Core Features: Hero section with headline, subtext, and early-access signup form; Features grid (3 highlight cards); Product teaser section with image mock placeholder; Testimonial carousel with 3 sample quotes; Footer with social links. Visual Vibes: Minimal, soft gradients, rounded corners. Colors: lavender, cream, midnight blue.' },
      { title: 'Event registration landing page', prompt: 'Build a landing page for our live online event "Future of Creative AI Summit." Purpose: explain the event, highlight speakers, and collect registrations. Core Features: Hero with event title, date/time, and "Register Now" form; Speakers section (3 profiles with names + roles); Agenda preview (timeline list); Testimonials from past attendees; Footer with contact + FAQ links. Visual Vibes: Minimal, soft gradients, rounded corners. Colors: lavender, cream, midnight blue.' },
      { title: 'Newsletter signup landing page', prompt: 'Build a newsletter signup landing page for our weekly industry insights newsletter "Signal Weekly." Purpose: convert visitors into subscribers with sample issues and lead magnet teasers. Core Features: Hero with headline + subtext + email signup field; "What You\'ll Get" 3-card value proposition grid; Sample newsletter preview section (mock article cards); Testimonial carousel (3 quotes from subscribers); Footer with archive + social links. Visual Vibes: Minimal, soft gradients, rounded corners. Colors: lavender, cream, midnight blue.' },
      { title: 'Build waitlist landing page', prompt: 'Build a waitlist landing page for our upcoming fintech app "Cashly." Purpose: build pre-launch hype, collect emails, and reward early adopters with referral tracking. Core Features: Hero section with countdown timer and email capture form; Referral progress tracker (show position in queue); "Why Join Early" benefits grid (3 cards); Social proof counter (X people already signed up); Footer with social links and company info. Visual Vibes: Minimal, soft gradients, rounded corners. Colors: mint green, charcoal, white.' },
      { title: 'Agency services landing page', prompt: 'Build a landing page for our branding agency "Studio Forma." Purpose: attract potential clients, showcase services, and generate consultation requests. Core Features: Hero with bold tagline and "Book a Call" CTA; Services grid (Brand Strategy, Visual Identity, Digital Design); Client logos carousel; Featured case study preview section; Footer with contact form and office locations. Visual Vibes: Minimal, soft gradients, rounded corners. Colors: off-white, black, terracotta accents.' },
      { title: 'App download landing page', prompt: 'Build a mobile app download landing page for our enterprise communication app "PulseConnect." Purpose: drive iOS and Android app downloads with compelling feature highlights. Core Features: Hero with phone mockup and app store buttons; Feature highlights (3 sections); Screenshot carousel showing app screens; User ratings and review snippets; Footer with download links and support. Visual Vibes: Minimal, soft gradients, rounded corners. Colors: electric blue, dark gray, white.' },
    ],
  },
  {
    name: 'Dashboard',
    ideas: [
      { title: 'Analytics dashboard', prompt: "Build an analytics dashboard for our SaaS tool 'MetricFlow.' Purpose: show KPIs and charts in a clean, glanceable layout. Core Features: KPI cards (Revenue, Active Users, Conversions); Line chart + bar chart sections; Filter bar (date range, segment); Data table of recent activity; Sidebar navigation. Visual Vibes: Minimal, rounded corners. Colors: white and pastel colours." },
      { title: 'Project management dashboard', prompt: "Build a project management dashboard for our team workspace 'TaskHarbor.' Purpose: track tasks, view team progress, and manage deadlines. Core Features: Kanban board (To Do / In Progress / Done); Team panel with avatars and roles; Task detail modal; Calendar or timeline section; Sidebar with project navigation. Visual Vibes: Minimal, soft gradients, rounded corners." },
      { title: 'Sales tracking dashboard', prompt: "Build a sales tracking dashboard for our CRM 'PipelinePro.' Purpose: visualize revenue trends, deals in progress, and rep performance. Core Features: KPI cards (Monthly Revenue, Win Rate, Deals Closed); Charts: sales funnel + revenue over time; Table of active deals with statuses; Rep leaderboard; Sidebar for navigation. Visual Vibes: Minimal, soft gradients, rounded corners." },
      { title: 'HR dashboard', prompt: "Build an HR dashboard for our workforce management tool 'TeamPulse.' Purpose: track employee metrics, attendance, and engagement scores. Core Features: KPI cards (Headcount, Turnover Rate, Engagement Score); Attendance heatmap by department; Employee satisfaction trend chart; Recent hire and departure feed; Sidebar with HR module navigation. Visual Vibes: Minimal, rounded corners. Colors: white, soft teal, coral highlights." },
      { title: 'Marketing performance dashboard', prompt: "Build a marketing performance dashboard for our tool 'CampaignIQ.' Purpose: visualize campaign metrics, channel performance, and ROI. Core Features: KPI cards (Ad Spend, Impressions, CTR, ROAS); Channel breakdown chart (Social, Search, Email); Campaign comparison table with status badges; Budget allocation donut chart; Sidebar with campaign navigation. Visual Vibes: Minimal, soft gradients, rounded corners." },
      { title: 'Inventory management dashboard', prompt: "Build an inventory management dashboard for our tool 'StockFlow.' Purpose: monitor stock levels, reorder alerts, and warehouse distribution. Core Features: KPI cards (Total SKUs, Low Stock Alerts, Orders Pending); Stock level bar chart by category; Reorder threshold alerts list; Warehouse location map view; Sidebar with inventory modules. Visual Vibes: Minimal, soft gradients, rounded corners." },
    ],
  },
  {
    name: 'Portfolio',
    ideas: [
      { title: 'Product designer portfolio website', prompt: "Build a portfolio website for a product designer named 'Ava Lin.' Purpose: showcase projects, design philosophy, and contact info. Core Features: Hero with name, role, and tagline; Project grid (3 featured projects); Case study preview cards; Testimonial carousel from collaborators; Footer with contact + socials. Visual Vibes: Minimal, dark. Colors: black, cool tone dark purple and navy." },
      { title: 'Photographer showcase portfolio page', prompt: "Build a portfolio page for a commercial photographer named 'Jasper Hale.' Purpose: showcase gallery images and promote booking requests for corporate events, product shoots, and headshots. Core Features: Hero with portrait + tagline; Masonry photo gallery with category filter (Corporate, Product, Editorial); Testimonials from business clients; Footer with booking form link. Visual Vibes: Minimal, soft gradients. Colors: pastel green, warm yellow." },
      { title: 'Build content creator profile page', prompt: "Build a personal profile page for a content creator and brand ambassador named 'Mira Vox.' Purpose: highlight video content, podcast episodes, brand partnerships, and social links. Core Features: Hero with avatar, name, and creator tagline; Featured content section (videos/podcasts); Brand partnership showcase; Newsletter signup block; Footer with all social profiles. Visual Vibes: Minimal, soft gradients, rounded corners." },
      { title: 'Build full-stack developer portfolio', prompt: "Build a portfolio website for a full-stack developer named 'Marcus Chen.' Purpose: showcase coding projects, technical skills, and open-source contributions. Core Features: Hero with name, tech stack icons, and GitHub link; Project grid with live demo and repo links; Skills matrix with proficiency indicators; Blog/writing section for technical articles; Footer with contact form and resume download. Visual Vibes: Minimal, dark. Colors: black, neon green, slate gray." },
      { title: 'Build digital illustrator portfolio page', prompt: "Build a portfolio page for a digital illustrator named 'Zoe Park.' Purpose: display artwork collections and attract commission requests from brands and agencies. Core Features: Hero with featured artwork and artist statement; Gallery grid with lightbox zoom; Commission pricing tiers section; Process showcase (sketch to final); Footer with commission form and social links. Visual Vibes: Minimal, soft gradients, rounded corners." },
      { title: 'Build architect portfolio website', prompt: "Build a portfolio website for an architect named 'Daniel Reyes.' Purpose: present architectural projects with rich visuals and project details. Core Features: Hero with dramatic project image and firm name; Project grid with hover reveal details; Case study pages with floor plans and renders; Awards and publications section; Footer with studio contact and location. Visual Vibes: Minimal, dark. Colors: concrete gray, white, warm wood tones." },
    ],
  },
  {
    name: 'Corporate',
    ideas: [
      { title: 'Build tech company website', prompt: "Build a tech company website called 'NovaTech Systems.' Purpose: showcase products, thought leadership, and enterprise credibility. Core Features: Product overview with interactive comparison; Case study carousel with expandable modals; Multi-author insights/blog hub; Investor & press center with downloadable reports; Global search. Visual Vibes: Sleek enterprise tech aesthetic. Colors: cobalt blue, charcoal, silver." },
      { title: 'Build law firm website', prompt: "Build a law firm website called 'Evergreen Legal Partners.' Purpose: establish credibility, showcase expertise, and drive consultation requests. Core Features: Attorney directory with filters; Attorney profile pages with publications and credentials; Knowledge center with legal guides; Multi-step consultation request form; Compliance-ready footer. Visual Vibes: Authoritative, refined. Colors: navy, ivory, dark green." },
      { title: 'Build consulting agency website', prompt: "Build a consulting agency website called 'Stratify Consulting.' Purpose: highlight expertise, showcase client results, and attract enterprise leads. Core Features: Dynamic services breakdown with interactive diagrams; Client results dashboard (KPIs, before/after metrics); Case study explorer with filters; Multi-step lead qualification form; Insights hub with analyst reports. Visual Vibes: Premium, polished. Colors: deep purple, champagne gold, graphite." },
      { title: 'Build healthcare company website', prompt: "Build a healthcare company website called 'VitalPath Medical.' Purpose: establish trust, explain services, and facilitate patient inquiries. Core Features: Service directory with specialty filters; Provider profiles with credentials; Patient resources center; Location finder with maps; Footer with emergency info and patient portal. Visual Vibes: Clean, trustworthy. Colors: medical blue, white, soft green." },
      { title: 'Build financial services website', prompt: "Build a wealth management firm website called 'Meridian Capital.' Purpose: convey expertise, showcase services, and attract high-net-worth clients. Core Features: Services overview with expandable details; Team directory with partner profiles; Insights hub with market commentary; Client login portal; Footer with disclosures and regulatory info. Visual Vibes: Premium, confidence-inspiring. Colors: deep green, gold, charcoal." },
      { title: 'Build nonprofit organization website', prompt: "Build a nonprofit website called 'BrightHorizon Foundation.' Purpose: share mission, highlight impact, and drive donations. Core Features: Impact statistics with animated counters; Program showcase with beneficiary stories; Donation flow with suggested amounts; Volunteer signup and event calendar; Footer with annual reports. Visual Vibes: Warm, hopeful. Colors: sunshine yellow, sky blue, white." },
    ],
  },
  {
    name: 'SaaS',
    ideas: [
      { title: 'Build CRM portal for SaaS platform', prompt: "Build a CRM portal for our SaaS platform 'ClientSphere.' Purpose: manage customer records, interactions, and pipeline stages. Core Features: Dashboard header with user greeting; Contact list with filters and search; Customer profile pages with notes; Pipeline stages board (Kanban-style); Footer with quick links. Visual Vibes: Clean enterprise UI. Colors: navy, slate gray, sky blue." },
      { title: 'Build sales lead tracker tool', prompt: "Build a sales lead tracker for our SaaS product 'LeadFlow.' Purpose: track inbound leads, their statuses, and rep assignments. Core Features: Hero dashboard with lead summary metrics; Lead table with sortable columns and status tags; Lead detail drawer with activity log; Conversion funnel mini-chart; Footer with integrations links. Visual Vibes: Modern SaaS aesthetic. Colors: teal, white, charcoal, neon mint accents." },
      { title: 'Build KPI management tool', prompt: "Build a KPI management tool for our SaaS analytics suite 'PulseMetrics.' Purpose: track, visualize, and manage company KPIs. Core Features: Headline KPI cards (Revenue, Retention, Engagement); Chart section showing trends over time; KPI editor panel (add/edit targets); Team comparison view; Footer with export options. Visual Vibes: Data-focused, calm, minimal. Colors: indigo, off-white, coral accents." },
      { title: 'Build customer support platform', prompt: "Build a helpdesk SaaS interface called 'TicketStream.' Purpose: manage support tickets, live chat, and knowledge base. Core Features: Dashboard with ticket volume and response time metrics; Ticket queue with priority tags; Conversation thread view with internal notes; Knowledge base article browser; Footer with API docs links. Visual Vibes: Modern SaaS aesthetic. Colors: sky blue, white, orange accent." },
      { title: 'Build appointment scheduling tool', prompt: "Build a scheduling SaaS tool called 'CalSync.' Purpose: allow businesses to manage bookings, availability, and client appointments. Core Features: Weekly calendar view with drag-and-drop slots; Appointment type configurator; Client booking page preview; Upcoming appointments list with reminders; Footer with calendar integrations. Visual Vibes: Clean enterprise UI. Colors: forest green, cream, slate." },
      { title: 'Build email marketing platform', prompt: "Build an email marketing SaaS called 'MailCraft.' Purpose: create campaigns, manage subscribers, and track email performance. Core Features: Dashboard with open rates, click rates, and subscriber growth; Drag-and-drop email builder preview; Campaign list with status and schedule; Subscriber segments table; Footer with templates library. Visual Vibes: Data-focused, calm, minimal. Colors: coral, white, charcoal." },
    ],
  },
  {
    name: 'Link-in-bio',
    ideas: [
      { title: 'Build Instagram creator link page', prompt: "Build a link-in-bio page for our brand's social media presence. Purpose: centralize product links, campaign pages, and content hubs. Core Features: Smart link buttons with analytics tracking; Carousel for featured campaigns; Shoppable gallery with product cards; Newsletter signup block; Tiered link groups. Visual Vibes: On-brand, professional. Colors: customizable to brand palette." },
      { title: 'Build musician multi-platform link hub', prompt: "Build a multi-platform link hub for our company 'EchoWave.' Purpose: direct visitors to our products, social channels, career page, and press resources from a single branded page. Core Features: Product link buttons with descriptions; Social media platform buttons with icons; Career page and press kit links; Newsletter signup; Company branding throughout. Visual Vibes: Professional, branded. Colors: company brand palette." },
      { title: 'Build beauty influencer link page', prompt: "Build a brand partnership showcase page called 'LinkLuxe.' Purpose: promote sponsored content, brand partnerships, and product collaborations. Core Features: Featured sponsor banner with swipeable promos; Collapsible category groups (Products, Services, Deals, Partners); Analytics-enabled link cards; Brand partnership showcase with logos; Media carousel. Visual Vibes: High-end, glossy, premium. Colors: black, cream, metallic gold." },
      { title: 'Build freelancer service link page', prompt: "Build a freelancer link page called 'HireMe.link.' Purpose: showcase services, portfolio samples, and booking options. Core Features: Service offerings with pricing hints; Portfolio preview carousel; Testimonial highlights from clients; Booking calendar link button; Footer with all contact methods. Visual Vibes: Professional yet approachable. Colors: coral, white, dark gray." },
      { title: 'Build executive CEO personal brand page', prompt: "Build an executive personal brand page for our CEO. Purpose: establish thought leadership, promote speaking engagements, and share publications. Core Features: Bio section with professional headshot; Published articles and book links; Speaking engagement calendar; Media kit download button; Footer with agent contact and social links. Visual Vibes: Literary, elegant, executive. Colors: deep navy, cream, gold." },
      { title: 'Build corporate podcast hub page', prompt: "Build a corporate podcast hub page called 'TuneIn.bio.' Purpose: direct listeners to episodes, platforms, and sponsorship inquiries. Core Features: Latest episode player embed; Platform buttons (Spotify, Apple, YouTube); Guest application form link; Sponsorship inquiry section; Footer with media kit and contact. Visual Vibes: Audio-forward, professional. Colors: deep purple, white, coral." },
    ],
  },
  {
    name: 'E-commerce',
    ideas: [
      { title: 'Build DIY online fashion store', prompt: "Build an online store for our DTC fashion brand 'CrochetEra.' Purpose: showcase collections and drive product purchases. Core Features: Hero with featured collection banner; Product grid with filters (size, color, category); Product detail pages with gallery + add-to-cart; Recommended items carousel; Footer with store policies. Visual Vibes: Soft gradients, modern. Colors: cream, soft shadows." },
      { title: 'Build digital products marketplace', prompt: "Build a digital products marketplace called 'PixelShelf.' Purpose: sell digital assets like templates, design resources, and business tools. Core Features: Hero with marketplace tagline and search bar; Product grid with category filters; Product detail page with preview + instant download; Creator spotlight carousel; Stripe checkout integration. Visual Vibes: Creative and vibrant. Colors: purple, cyan, white." },
      { title: 'Build subscription box service website', prompt: "Build a subscription box service website called 'PeanutCrate.' Purpose: convert visitors into monthly subscription customers. Core Features: Hero with subscription value proposition + CTA; 'How it works' 3-step grid; Box preview carousel; Pricing tiers with monthly/annual toggle; Stripe subscription billing integration. Visual Vibes: Friendly, playful, warm. Colors: sunshine yellow, coral, sand beige." },
      { title: 'Build B2B wholesale vintage marketplace', prompt: "Build a B2B wholesale marketplace called 'TradeVault.' Purpose: connect suppliers with business buyers for bulk purchasing. Core Features: Hero with curated supplier finds banner; Product grid with category and MOQ filters; Product detail with supplier info and bulk pricing; Supplier storefront pages; Footer with buyer guide and support. Visual Vibes: Professional, trustworthy. Colors: navy, white, amber accents." },
      { title: 'Build SaaS pricing and checkout page', prompt: "Build a SaaS product pricing and checkout page for our platform. Purpose: present pricing tiers, feature comparison, and streamlined checkout. Core Features: Hero with value proposition; Pricing tiers with feature comparison table; Plan toggle (monthly/annual); Stripe checkout integration; FAQ section and footer with support. Visual Vibes: Clean, conversion-optimized. Colors: brand palette." },
      { title: 'Build artisan food E-commerce site', prompt: "Build an e-commerce site for our consumer brand 'HarvestTable.' Purpose: sell products with seasonal collections, brand storytelling, and gift customization. Core Features: Hero with seasonal collection spotlight; Product grid with category and dietary filters; Product detail with sourcing story and pairing suggestions; Gift box builder with customization; Footer with recipes and producer stories. Visual Vibes: Elegant. Colors: olive green, warm beige, burgundy." },
    ],
  },
  {
    name: 'Blog',
    ideas: [
      { title: 'Build SEO-driven personal blog', prompt: "Build an SEO-driven content marketing blog for our company. Purpose: drive organic traffic, generate leads, and establish thought leadership. Core Features: Featured post slider; Article pages supporting rich media; Category and tag filters; Newsletter integration with lead capture; Archive explorer. Visual Vibes: Modern editorial. Colors: soft white, charcoal, muted gold." },
      { title: 'Build tech news company blog', prompt: "Build a company blog and content hub for SEO-driven lead generation and thought leadership. Purpose: publish multi-author editorial content with professional workflow. Core Features: Breaking-news ticker + featured articles carousel; Multi-author editorial workflow; Article pages with code blocks, charts, and embeds; Search with autocomplete; Comparison tool for product reviews. Visual Vibes: Bold, high-contrast. Colors: electric blue, black, turquoise." },
      { title: 'Build internal engineering knowledge base', prompt: "Build an internal knowledge base for our engineering team. Purpose: centralize documentation, guides, and best practices. Core Features: Article directory with advanced filters (team, topic, difficulty); Step-by-step guide pages with code blocks; User-generated content: comments and ratings; Search with relevance scoring; Saved articles library. Visual Vibes: Clean, functional. Colors: white, slate, green accents." },
      { title: 'Build customer self-service help center', prompt: "Build a customer-facing help center for our product. Purpose: enable self-service support with searchable documentation. Core Features: Hero with search bar; Category-based article navigation; Step-by-step guide pages with screenshots; FAQ section; Footer with contact support and ticket submission. Visual Vibes: Clean, helpful. Colors: brand palette with blue accents." },
      { title: 'Build industry research report platform', prompt: "Build an industry research report publishing platform. Purpose: publish gated research reports with data visualizations and subscription access. Core Features: Report directory with industry and topic filters; Report pages with executive summary and data charts; Gated download with email capture; Popular reports sidebar; Footer with subscription options. Visual Vibes: Professional, data-rich. Colors: navy, white, gold accents." },
      { title: 'Build immersive brand storytelling blog', prompt: "Build an immersive brand storytelling blog called 'LensStories.' Purpose: publish visual narratives that showcase our brand's impact and culture. Core Features: Hero with immersive featured story; Story grid with full-bleed thumbnails; Story pages with cinematic scroll experience; Behind-the-scenes section; Footer with media inquiries. Visual Vibes: Dramatic, gallery-like. Colors: black, white, subtle warm tones." },
    ],
  },
  {
    name: 'Mini Games',
    ideas: [
      { title: 'Build branded trivia game for marketing', prompt: 'Build a branded trivia game called "QuizRipple" for our marketing campaign. Purpose: engage potential customers with fun product-related quizzes, capture leads, and boost brand awareness.\nCore Features:\n- Category selection (Industry Trends, Product Knowledge, Fun Facts)\n- Timed multiple-choice question rounds\n- Streak + combo bonus system\n- Leaderboard with prize tiers for top scorers\n- Lead capture form with email opt-in after game\nVisual Vibes:\nBright, playful, on-brand. Colors: brand palette with fun accents.' },
      { title: 'Build gamified vocabulary training tool', prompt: 'Build a gamified vocabulary training tool called "LexiLoops" for corporate learning. Purpose: help employees master industry terminology and product vocabulary through daily word puzzles.\nCore Features:\n- Daily puzzle hub (Term Scramble, Definition Match, Fill-in-the-blanks)\n- Custom puzzle creation from company glossary\n- Difficulty selector (Beginner, Intermediate, Expert)\n- Hint and reveal mechanics\n- Progress tracker with streaks and team leaderboard\nVisual Vibes:\nCrisp, letter-tile aesthetic with subtle shadows. Colors: off-white, ink black, pastel teal and orange accents.' },
      { title: 'Build gamified team goal tracker', prompt: 'Build a gamified team goal tracker called "QuestStreak." Purpose: turn quarterly OKRs and team goals into quests with XP, levels, and milestone rewards to boost engagement.\nCore Features:\n- Goal list displayed as "quests" with daily/weekly milestones\n- XP and level-up system tied to goal completion\n- Badge collection for team achievements\n- Streak calendar view with visual heatmap\n- Team rewards shop (extra PTO, lunch vouchers, swag)\nVisual Vibes:\nFriendly RPG-lite look with soft cards and icons. Colors: forest green, gold, soft indigo, with warm gradients.' },
      { title: 'Build branded memory match game', prompt: 'Build a branded memory matching game called "PairUp" for trade shows and campaigns. Purpose: engage booth visitors or online audiences by matching product features with benefits.\nCore Features:\n- Theme selector (Products, Features, Team Members)\n- Grid sizes for difficulty (4x4, 6x6, 8x8)\n- Move counter and timer\n- Best score tracking with prize entry for top scorers\n- Lead capture and social sharing after completion\nVisual Vibes:\nPlayful, card-game aesthetic with brand elements. Colors: soft purple, mint green, white.' },
      { title: 'Build team reaction speed test game', prompt: 'Build a team icebreaker reaction game called "QuickTap." Purpose: energize meetings and team events with fun competitive challenges.\nCore Features:\n- Start screen with game instructions\n- Random-delay tap target appearance\n- Reaction time display in milliseconds\n- Live multiplayer mode for team competitions\n- Team leaderboard with session history\nVisual Vibes:\nMinimal, high-contrast, speed-focused. Colors: black, neon green, white.' },
      { title: 'Build daily data literacy number puzzle', prompt: 'Build a data literacy training game called "NumCrunch" for analytics teams. Purpose: sharpen quantitative reasoning with daily number challenges tied to business metrics.\nCore Features:\n- Daily puzzle with target business metric\n- Number tiles and operation buttons\n- Hint system with limited uses\n- Streak counter and team challenge mode\n- Past puzzles archive with explanations\nVisual Vibes:\nClean, puzzle-focused, newspaper-game inspired. Colors: cream, navy, red accents.' },
    ],
  },
  {
    name: 'Productivity',
    ideas: [
      { title: 'Build advanced team task management app', prompt: "Build an advanced task management app called 'TaskNest.' Purpose: help teams collaborate and manage complex workflows. Core Features: Multi-project dashboard with drag-and-drop Kanban; Task detail drawer with subtasks, attachments, comments; Calendar view; Analytics panel; Team collaboration tools. Visual Vibes: Focused, sophisticated. Colors: sky blue, cool gray, bright coral accents." },
      { title: 'Build OKR tracking tool for teams', prompt: "Build an OKR tracking tool for cross-functional teams. Purpose: align goals across departments with transparent progress tracking. Core Features: OKR hierarchy view (Company > Team > Individual); Key result progress bars with check-ins; Team alignment dashboard; Weekly check-in prompts; Export and reporting. Visual Vibes: Clean, goal-oriented. Colors: brand palette." },
      { title: 'Build intelligent time tracking software', prompt: "Build an advanced time tracking software called 'Clocklytics.' Purpose: analyze productivity patterns and support client billing. Core Features: Intelligent timer with idle detection; Weekly/monthly reporting with charts; Project-based time allocation with hourly rates; Invoice generator; Calendar sync. Visual Vibes: Precise, data-forward. Colors: dark navy, aqua blue, silver." },
      { title: 'Build client project status portal', prompt: "Build a client project status portal. Purpose: give clients real-time visibility into project progress, milestones, and deliverables. Core Features: Project dashboard with milestone timeline; Deliverable status cards; Document sharing area; Activity feed with updates; Client feedback form. Visual Vibes: Professional, transparent. Colors: brand palette." },
      { title: 'Build team timesheet reporting tool', prompt: "Build a team timesheet reporting tool. Purpose: track project-level time, analyze utilization, and generate client billing reports. Core Features: Timesheet entry with project/task selection; Utilization analysis dashboard; Client billing report generator; Team overview with hours breakdown; Export to CSV/PDF. Visual Vibes: Data-forward, professional. Colors: brand palette." },
      { title: 'Build smart email productivity tool', prompt: "Build an email productivity tool called 'InboxZen.' Purpose: help users process email faster with smart categorization and templates. Core Features: Inbox dashboard with category counts; Email triage view with quick actions; Template library with variables; Follow-up reminder scheduler; Footer with analytics and settings. Visual Vibes: Clean, efficient. Colors: white, light blue, green success states." },
    ],
  },
]

export default data
